remove dist from git
kushal@fedora:~/src/ts/kphoto$ cd ~/src/ts/kphoto/; time bash export.sh > docs/llm/vendor/output.txt; time yarn; time yarn run build

real	0m0.502s
user	0m0.258s
sys	0m0.313s
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done in 6.05s.

real	0m6.175s
user	0m4.696s
sys	0m1.942s
yarn run v1.22.22
$ tsc && vite build
vite v8.1.4 building client environment for production...
✓ 9 modules transformed.
computing gzip size...
dist/index.html                  0.45 kB │ gzip: 0.29 kB
dist/assets/vite-BF8QNONU.svg    8.70 kB │ gzip: 1.60 kB
dist/assets/hero-CLDdwZDr.png   13.05 kB
dist/assets/index-CsUDhMuy.css   4.10 kB │ gzip: 1.46 kB
dist/assets/index-B4vdZNPd.js    4.52 kB │ gzip: 2.02 kB

✓ built in 50ms
Done in 0.27s.

real	0m0.382s
user	0m0.321s
sys	0m0.236s
kushal@fedora:~/src/ts/kphoto$ time yarn outdated
yarn outdated v1.22.22
Done in 1.54s.

real	0m1.671s
user	0m0.443s
sys	0m0.216s
kushal@fedora:~/src/ts/kphoto$ git rm --cached dist
fatal: not removing 'dist' recursively without -r
kushal@fedora:~/src/ts/kphoto$ time git rm --cached --recursive dist
error: unknown option `recursive'
usage: git rm [-f | --force] [-n] [-r] [--cached] [--ignore-unmatch]
              [--quiet] [--pathspec-from-file=<file> [--pathspec-file-nul]]
              [--] [<pathspec>...]

    -n, --[no-]dry-run    dry run
    -q, --[no-]quiet      do not list removed files
    --[no-]cached         only remove from the index
    -f, --[no-]force      override the up-to-date check
    -r                    allow recursive removal
    --[no-]ignore-unmatch exit with a zero status even if nothing matched
    --[no-]sparse         allow updating entries outside of the sparse-checkout cone
    --[no-]pathspec-from-file <file>
                          read pathspec from file
    --[no-]pathspec-file-nul
                          with --pathspec-from-file, pathspec elements are separated with NUL character

real	0m0.002s
user	0m0.000s
sys	0m0.002s
kushal@fedora:~/src/ts/kphoto$ time git rm --cached -r dist
rm 'dist/assets/hero-CLDdwZDr.png'
rm 'dist/assets/index-B4vdZNPd.js'
rm 'dist/assets/index-CsUDhMuy.css'
rm 'dist/assets/vite-BF8QNONU.svg'
rm 'dist/favicon.svg'
rm 'dist/icons.svg'
rm 'dist/index.html'

real	0m0.004s
user	0m0.001s
sys	0m0.003s
kushal@fedora:~/src/ts/kphoto$